package fswalk

import (
	"os"
	"path/filepath"
	"testing"
)

func TestWalkBasic(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "main.go", "package main")
	writeFile(t, dir, "util.go", "package main")
	writeFile(t, dir, "readme.md", "# readme")

	candidates, err := Walk(dir, []string{"**/*.go"}, nil, 0)
	if err != nil {
		t.Fatal(err)
	}
	if len(candidates) != 2 {
		t.Errorf("expected 2 candidates, got %d", len(candidates))
	}
	for _, c := range candidates {
		if c.Language != "go" {
			t.Errorf("expected language go, got %s", c.Language)
		}
	}
}

func TestWalkExclude(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "main.go", "package main")
	if err := os.MkdirAll(filepath.Join(dir, "vendor"), 0o755); err != nil {
		t.Fatal(err)
	}
	writeFile(t, dir, "vendor/dep.go", "package dep")

	candidates, err := Walk(dir, []string{"**/*.go"}, []string{"vendor/**"}, 0)
	if err != nil {
		t.Fatal(err)
	}
	if len(candidates) != 1 {
		t.Errorf("expected 1 candidate, got %d", len(candidates))
	}
}

func TestWalkMaxSize(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "small.go", "package main")
	writeFile(t, dir, "big.go", string(make([]byte, 2048)))

	candidates, err := Walk(dir, []string{"**/*.go"}, nil, 1024)
	if err != nil {
		t.Fatal(err)
	}
	if len(candidates) != 1 {
		t.Errorf("expected 1 candidate (small), got %d", len(candidates))
	}
}

func TestWalkLanguageDetection(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "main.go", "package main")
	writeFile(t, dir, "app.ts", "export const x = 1")
	writeFile(t, dir, "app.tsx", "export const x = 1")
	writeFile(t, dir, "util.js", "module.exports = {}")
	writeFile(t, dir, "util.jsx", "module.exports = {}")

	candidates, err := Walk(dir, []string{"**/*.go", "**/*.ts", "**/*.tsx", "**/*.js", "**/*.jsx"}, nil, 0)
	if err != nil {
		t.Fatal(err)
	}
	if len(candidates) != 5 {
		t.Errorf("expected 5 candidates, got %d", len(candidates))
	}

	langs := map[string]int{}
	for _, c := range candidates {
		langs[c.Language]++
	}
	if langs["go"] != 1 {
		t.Errorf("expected 1 go file, got %d", langs["go"])
	}
	if langs["typescript"] != 2 {
		t.Errorf("expected 2 typescript files, got %d", langs["typescript"])
	}
	if langs["javascript"] != 2 {
		t.Errorf("expected 2 javascript files, got %d", langs["javascript"])
	}
}

func TestWalkGeneratedFile(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "normal.go", "package main")
	writeFile(t, dir, "gen.go", "// Code generated by tool; DO NOT EDIT.\npackage main")
	if err := os.MkdirAll(filepath.Join(dir, "generated"), 0o755); err != nil {
		t.Fatal(err)
	}
	writeFile(t, dir, "generated/stuff.go", "package gen")

	candidates, err := Walk(dir, []string{"**/*.go"}, nil, 0)
	if err != nil {
		t.Fatal(err)
	}

	genCount := 0
	for _, c := range candidates {
		if c.IsGenerated {
			genCount++
		}
	}
	if genCount != 2 {
		t.Errorf("expected 2 generated files, got %d", genCount)
	}
}

func TestDetectLanguage(t *testing.T) {
	tests := []struct {
		path string
		want string
	}{
		{"main.go", "go"},
		{"app.ts", "typescript"},
		{"app.tsx", "typescript"},
		{"util.js", "javascript"},
		{"util.jsx", "javascript"},
		{"readme.md", ""},
		{"Makefile", ""},
	}
	for _, tt := range tests {
		got := DetectLanguage(tt.path)
		if got != tt.want {
			t.Errorf("DetectLanguage(%q) = %q, want %q", tt.path, got, tt.want)
		}
	}
}

func writeFile(t *testing.T, dir, rel, content string) {
	t.Helper()
	path := filepath.Join(dir, rel)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}
